### ISSUE TITLE
Installation does not work.

### ISSUE THREAD

**Issue by SchafferApp** [soef/ioBroker.hid#14]
Installation does not work.

npm install iobroker.hid

> node-hid@0.5.7 install /opt/iobroker/node_modules/node-hid
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.15.0 runtime=node arch=arm platform=linux)
make: Verzeichnis „/opt/iobroker/node_modules/node-hid/build“ wird betreten
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: Datei oder Verzeichnis nicht gefunden
 #include <libusb.h>
                    ^
compilation terminated.
hidapi.target.mk:101: die Regel für Ziel „Release/obj.target/hidapi/hidapi/libusb/hid.o“ scheiterte
make: *** [Release/obj.target/hidapi/hidapi/libusb/hid.o] Fehler 1
make: Verzeichnis „/opt/iobroker/node_modules/node-hid/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.98-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/node-hid
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/sqlite3/package.json'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-hid@0.5.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-hid@0.5.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-02-28T16_35_52_589Z-debug.log

**Comment by jogibear9988** [comment]
This issue was moved to iobroker-community-adapters/ioBroker.hid-community#5

**Comment by SchafferApp** [comment]
???

**Comment by jogibear9988** [comment]
we moved the adapters to iobroker community cause soef does not seem to maintain them any more
