### ISSUE TITLE
Kann es nicht instalieren

### ISSUE THREAD

**Issue by SchafferApp** [soef/ioBroker.hid#9]
Ich habe es erst im ioBroker versucht. Jedoch hat das nicht geklappt. Dann habe ich es per Terminal versucht. Dort lässt es sich aber auch nicht installieren. Ich weiß leider nichts mit den ganzen Fehlermeldung an zu fangen.

pi@pi01:/opt/iobroker $ sudo npm install iobroker.hid

> authenticate-pam@1.0.2 install /opt/iobroker/node_modules/authenticate-pam
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.13.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
make: Verzeichnis „/opt/iobroker/node_modules/authenticate-pam/build“ wird betreten
  CXX(target) Release/obj.target/authenticate_pam/authenticate_pam.o
../authenticate_pam.cc:30:31: fatal error: security/pam_appl.h: Datei oder Verzeichnis nicht gefunden
 #include <security/pam_appl.h>
                               ^
compilation terminated.
authenticate_pam.target.mk:92: die Regel für Ziel „Release/obj.target/authenticate_pam/authenticate_pam.o“ scheiterte
make: *** [Release/obj.target/authenticate_pam/authenticate_pam.o] Fehler 1
make: Verzeichnis „/opt/iobroker/node_modules/authenticate-pam/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.59-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/authenticate-pam
gyp ERR! node -v v6.13.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

> node-hid@0.5.7 install /opt/iobroker/node_modules/node-hid
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/node-hid-v0.5.7-node-v48-linux-arm.tar.gz
prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.13.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
make: Verzeichnis „/opt/iobroker/node_modules/node-hid/build“ wird betreten
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: Datei oder Verzeichnis nicht gefunden
 #include <libusb.h>
                    ^
compilation terminated.
hidapi.target.mk:94: die Regel für Ziel „Release/obj.target/hidapi/hidapi/libusb/hid.o“ scheiterte
make: *** [Release/obj.target/hidapi/hidapi/libusb/hid.o] Fehler 1
make: Verzeichnis „/opt/iobroker/node_modules/node-hid/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.59-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/node-hid
gyp ERR! node -v v6.13.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 (node_modules/authenticate-pam):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Linux 4.9.59-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "iobroker.hid"
npm ERR! node v6.13.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-hid@0.5.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-hid@0.5.7 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-hid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-hid
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-hid
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/iobroker/npm-debug.log

**Comment by soef** [comment]
Hallo, so wie es aussieht sind Voraussetzungen die zum Erstellen oder Kompilieren von "node_modules", die iobroker.hid voraussetzt, nicht gegeben.
Versuche einmal 
sudo apt-get install build-essential
und eine ermeute Instalation von iobroker.hid

**Comment by SchafferApp** [comment]
hilft leider nicht.

pi@pi01:/opt/iobroker $ sudo npm install iobroker.hid

> authenticate-pam@1.0.2 install /opt/iobroker/node_modules/authenticate-pam
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.13.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/iobroker/node_modules/authenticate-pam/.node-gyp"
make: Verzeichnis „/opt/iobroker/node_modules/authenticate-pam/build“ wird betreten
  CXX(target) Release/obj.target/authenticate_pam/authenticate_pam.o
../authenticate_pam.cc:30:31: fatal error: security/pam_appl.h: Datei oder Verzeichnis nicht gefunden
 #include <security/pam_appl.h>
                               ^
compilation terminated.
authenticate_pam.target.mk:92: die Regel für Ziel „Release/obj.target/authenticate_pam/authenticate_pam.o“ scheiterte
make: *** [Release/obj.target/authenticate_pam/authenticate_pam.o] Fehler 1
make: Verzeichnis „/opt/iobroker/node_modules/authenticate-pam/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.59-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/authenticate-pam
gyp ERR! node -v v6.13.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

> node-hid@0.5.7 install /opt/iobroker/node_modules/node-hid
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/node-hid-v0.5.7-node-v48-linux-arm.tar.gz
prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.13.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/iobroker/node_modules/node-hid/.node-gyp"
make: Verzeichnis „/opt/iobroker/node_modules/node-hid/build“ wird betreten
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: Datei oder Verzeichnis nicht gefunden
 #include <libusb.h>
                    ^
compilation terminated.
hidapi.target.mk:94: die Regel für Ziel „Release/obj.target/hidapi/hidapi/libusb/hid.o“ scheiterte
make: *** [Release/obj.target/hidapi/hidapi/libusb/hid.o] Fehler 1
make: Verzeichnis „/opt/iobroker/node_modules/node-hid/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.59-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/node-hid
gyp ERR! node -v v6.13.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 (node_modules/authenticate-pam):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Linux 4.9.59-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "iobroker.hid"
npm ERR! node v6.13.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-hid@0.5.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-hid@0.5.7 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-hid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-hid
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-hid
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/iobroker/npm-debug.log

**Comment by soef** [comment]
Hallo, die Installation versucht das Module "node-hid" zu erstellen. Das schlägt aber fehl. Versuche doch einmal außerhalb des iobroker Verzeichnisses (z.b. in deinem Homeverzeichnis ~) npm install node-hid. (kannst Du später wieder entfernen). Wenn die Voraussetzungen dafür geschaffen sind, sollte sich auch iobroker.hid installieren lassen.

**Comment by noaboa97** [comment]
Hallo,

Bei mir funktioniert die Installation auch nicht. ioBroker ist aufem Raspberry installiert.

`sudo apt-get install build-essential` ausgeführt und die Installation hat nicht geklappt ins Home verzeichnis und im ioBroker auch nicht. 

Läuft es einfach auf dem Raspi nicht oder wie sieht das aus?

Hab ich dass richtig verstanden, dass man die Apple TV Remote dann gebrauche könnte um ioBroker States zu steuern? Geht dies auch dann auch mit der iOS Apple TV Remote?

**Comment by noaboa97** [comment]
Ich erhalte dann diese Fehlermeldung: Fertig mit Fehler: host.raspberrypi Cannot install hid

Mit folgender Consolenausgabe: 

$ ./iobroker add hid  --host raspberrypi
NPM version: 3.10.10
npm install iobroker.hid --production --save --prefix "/opt/iobroker" (System call)
prebuild-install
 WARN install EACCES: permission denied, access '/root/.npm'
gyp
 WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.11.1"gyp
 WARN EACCES attempting to reinstall using temporary dev dir "/opt/iobroker/node_modules/node-hid/.node-gyp"
../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory #include <libusb.h>
                    ^
compilation terminated.

make: *** [Release/obj.target/hidapi/hidapi/libusb/hid.o] Error 1
gyp
 ERR!
 build error 
gyp
 ERR! 
stack Error: `make` failed with exit code: 2gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.9.35-v7+
gyp ERR! 
command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/node-hid
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.4.0

gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/iobroker.radar/node_modules/noble/node_modules/xpc-connection):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/noble/node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/body-parser/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/express/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/send/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/setprototypeof/package.json'

npm ERR! Linux 4.9.35-v7+npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "iobroker.hid" "--production" "--save" "--prefix" "/opt/iobroker"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-hid@0.5.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-hid@0.5.7 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-hid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!
     npm bugs node-hidnpm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-hid
npm ERR! There is likely additional logging output above.


npm ERR! Please include the following file with any support request:npm ERR!     /home/npm-debug.log

host.raspberrypi install adapter hid
NPM version: 3.10.10
npm install iobroker.hid --production --save --prefix "/opt/iobroker" (System call)
prebuild-install
 
WARN install EACCES: permission denied, access '/root/.npm'
gyp
 WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.11.1"gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/iobroker/node_modules/node-hid/.node-gyp"

../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory #include <libusb.h>
                    ^
compilation terminated.

make: *** [Release/obj.target/hidapi/hidapi/libusb/hid.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

gyp ERR! System Linux 4.9.35-v7+gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /opt/iobroker/node_modules/node-hidgyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm
 WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/iobroker.radar/node_modules/noble/node_modules/xpc-connection):npm
 WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm
 WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/noble/node_modules/xpc-connection):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/body-parser/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/express/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/send/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/setprototypeof/package.json'

npm
 
ERR! Linux 4.9.35-v7+npm ERR! argv
 "/usr/local/bin/node" "/usr/local/bin/npm" "install" "iobroker.hid" "--production" "--save" "--prefix" "/opt/iobroker"npm ERR! node v6.11.1

npm ERR! npm  v3.10.10npm ERR! code ELIFECYCLE


npm ERR! node-hid@0.5.7 install: `prebuild-install || node-gyp rebuild`npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-hid@0.5.7 install script 'prebuild-install || node-gyp rebuild'.
npm ERR!
 Make sure you have the latest version of node.js and npm installed.npm ERR! If you do, this is most likely a problem with the node-hid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!
     npm bugs node-hidnpm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-hid
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/npm-debug.log

host.raspberrypi install adapter hid
NPM version: 3.10.10
npm install iobroker.hid --production --save --prefix "/opt/iobroker" (System call)
prebuild-install
 
WARN install EACCES: permission denied, access '/root/.npm'
gyp
 
WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.11.1"gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/iobroker/node_modules/node-hid/.node-gyp"

../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory #include <libusb.h>
                    ^
compilation terminated.

make: *** [Release/obj.target/hidapi/hidapi/libusb/hid.o] Error 1
gyp ERR! build error 
gyp ERR! 
stack Error: `make` failed with exit code: 2gyp 
ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)gyp
 ERR! stack     at emitTwo (events.js:106:13)gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

gyp ERR! System Linux 4.9.35-v7+gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/node-hid
gyp ERR! 
node -v v6.11.1gyp 
ERR! node-gyp -v v3.4.0
gyp
 ERR! not ok 
npm
 WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/iobroker.radar/node_modules/noble/node_modules/xpc-connection):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/noble/node_modules/xpc-connection):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/body-parser/package.json'

npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/express/package.json'npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/send/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/setprototypeof/package.json'

npm
 ERR! Linux 4.9.35-v7+npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "iobroker.hid" "--production" "--save" "--prefix" "/opt/iobroker"
npm ERR! 
node v6.11.1npm ERR! npm  v3.10.10

npm ERR! code ELIFECYCLE

npm ERR! node-hid@0.5.7 install: `prebuild-install || node-gyp rebuild`npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-hid@0.5.7 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-hid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm 
ERR!     prebuild-install || node-gyp rebuildnpm ERR! You can get information on how to open an issue for this project with:
npm ERR!
     npm bugs node-hid
npm ERR! Or if that isn't available, you can get their info via:npm ERR!     npm owner ls node-hid
npm ERR! There is likely additional logging output above.


npm ERR! Please include the following file with any support request:npm ERR!     /home/npm-debug.log

host.raspberrypi install adapter hid
ERROR: host.raspberrypi Cannot install hid
ERROR: process exited with code 13

**Comment by noaboa97** [comment]
Habe es geschafft...

Musst noch folgendes Paket installieren: libusb-1.0-0-dev
Hier den command
`
sudo apt-get install libusb-1.0-0-dev`

**Comment by jogibear9988** [comment]
This issue was moved to iobroker-community-adapters/ioBroker.hid-community#2
